### PR TITLE
fix white space around links

### PR DESCRIPTION
**Pull request by kapunahelewong**
This PR is a work in progress trying to fix the extra space that appears around links:

Screen Shot 2021-07-26 at 10 08 47 AM

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Preview: https://deploy-preview-93--cncf-hugo-starter.netlify.app/

**Review by chalin — CHANGES_REQUESTED** [review]
Make sure that the `render-link.html` file doesn't end with a newline. That is, the last character of the file must be `>`.

**Comment by kapunahelewong** [comment]
Oooh that worked perfectly. Thank you @chalin!!

**Review by chalin — APPROVED** [review]
LGTM

**Review by nate-double-u — APPROVED** [review]
/lgtm

Thanks @kapunahelewong!

**Review by nate-double-u — APPROVED** [review]
refreshing /lgtm

**Review by chalin — APPROVED** [review]
LGTM (though I'm not sure what your last commit changed relative to earlier).

**Comment by nate-double-u** [comment]
> LGTM (though I'm not sure what your last commit changed relative to earlier).

I had the same thing over on #86, the GitHub UI said the branch was out of date with `main`, but I didn't see how. Rebasing and force-pushing seems to have sorted it (but wipes out approvals)

**Comment by chalin** [comment]
Anything left to do here before this is merged @kapunahelewong? If not, please do the following:

- Add "Closes #45" to the opening comment if you believe that it closes the issue. (This will allow GitHub to close the issue once this PR is merged.)
- Go ahead an "squash 'n merge" this PR. (Generally, once you have received the necessary approvals for a PR, feel free to merge it.)

**Comment by chalin** [comment]
Oops, @nate-double-u, beat you to it. Well, for next time then :).

**Comment by nate-double-u** [comment]
(sorry, i merged it literally the same moment you posted that. I did link the issue before i did so 😅)

**Pull request merged**
