### PR TITLE
[WIP] Fix issues with DCO

### PR DESCRIPTION
**Pull request by celestehorgan**

### CODE REVIEW

**Comment by celestehorgan** [comment]
Commits in question: 
3364229  ~ 794c65a

**Comment by hackabletype** [comment]
No bot here...
Looks good to me. 👍

**Comment by celestehorgan** [comment]
This isn't ready to merge yet, though, and I'm not looking at it on the weekend. :)

**Comment by hackabletype** [comment]
> I'm not looking at it on the weekend. :)

Fair :)

**Pull request merged**
