### PR TITLE
Converting hugo config.toml file to config.yaml

### LINKED ISSUE #78: Convert TOML config to YAML

### PR DESCRIPTION
**Pull request by nate-double-u**
Fixes #78

diff shows no difference in build.

### CODE REVIEW

**Comment by nate-double-u** [comment]
/hold

I made a mistake on the commit message.

**Comment by nate-double-u** [comment]
/unhold

Commit comment fixed.

**Review by chalin — APPROVED** [review]
Thanks!

**Comment by chalin** [comment]
We'll want to review the content of this file at some point.

**Pull request merged**
